import './style.css';

type Good={id:string;name:string;mark:string;color:string;price:number;start:number;holding:number};
type Game={phase:'setup'|'playing'|'finished';cash:number;goods:Good[];seconds:number;total:number;headline:number;status:string;mute:boolean};
type Player={id:string;name:string;cash:number;holdings:number[];connected:boolean;isYou:boolean};
type Room={code:string;hostId:string;phase:'lobby'|'playing'|'finished';seconds:number;total:number;headline:string;goods:Omit<Good,'holding'>[];players:Player[];objective:string};
const base=[{id:'citrus',name:'Glowfruit',mark:'GF',color:'lime',price:38},{id:'vane',name:'Weather vane',mark:'WV',color:'plum',price:51},{id:'robot',name:'Tin robot',mark:'TR',color:'blue',price:44}];
const news=[['A lighthouse keeper orders Glowfruit lantern oil.',[8,-3,1]],['A gusty parade needs weather vanes.',[-2,9,0]],['The school fair wants tiny robot ushers.',[0,-2,10]],['A rain shower spoils one Glowfruit crate.',[-8,2,-1]]] as const;
const app=document.querySelector<HTMLDivElement>('#app')!;
let game:Game|null=null,room:Room|null=null,ws:WebSocket|null=null,last=0,acc=0,error='';
const roomKey='closing-bell:room';
const demo=()=>location.pathname==='/demo'||new URLSearchParams(location.search).get('demo')==='1';
const time=(s:number)=>Math.floor(s/60)+':'+String(Math.max(0,Math.ceil(s%60))).padStart(2,'0');
const nav=()=>'<header class="site-header"><a class="wordmark" href="/" data-route>Closing <span>Bell</span></a><nav aria-label="Primary"><a href="/" data-route>Rooms</a><a href="/demo" data-route>Demo</a><a href="/privacy" data-route>Privacy</a></nav></header>';
const foot=()=>'<footer><p>Closing Bell is a fictional-goods game for short group breaks.</p><p><a href="/privacy" data-route>Privacy</a> · <a href="/terms" data-route>Terms</a> · Built by Param Factory · v1.1</p><p class="generated">Market-floor art is AI-generated and original to this game.</p></footer>';
const progress=(s:number,t:number)=>'<progress class="progress" aria-label="'+time(s)+' remaining" value="'+s+'" max="'+t+'">'+time(s)+'</progress>';
function wireLinks(){app.querySelectorAll<HTMLAnchorElement>('[data-route]').forEach(a=>a.onclick=e=>{e.preventDefault();history.pushState({},'',a.getAttribute('href')!);game=null;room=null;route();});}
function notice(s:string){const n=app.querySelector('.route-note');if(n)n.textContent=s;}
function newGame():Game{const d=Number(new URLSearchParams(location.search).get('duration'));const total=Number.isFinite(d)&&d>0?d:90;return{phase:'setup',cash:180,goods:base.map(x=>({...x,start:x.price,holding:0})),seconds:total,total,headline:-1,status:'Choose a seat, then open the market.',mute:localStorage.getItem('closing-bell:mute')==='yes'};}
function route(){document.title=location.pathname==='/privacy'?'Privacy — Closing Bell':location.pathname==='/terms'?'Terms — Closing Bell':demo()?'Demo — Closing Bell':'Closing Bell — Play a room-code market game';document.querySelector<HTMLLinkElement>('link[rel="canonical"]')?.setAttribute('href','https://closing-bell.sociobot.in'+(location.pathname==='/demo'?'/demo':location.pathname==='/privacy'?'/privacy':location.pathname==='/terms'?'/terms':'/'));if(location.pathname==='/privacy'||location.pathname==='/terms'||location.pathname==='/404'){page(location.pathname);return;}if(!demo()){game=null;renderRoom();restore();return;}if(!game)game=newGame();renderDemo();}
function page(path:string){const privacy=path==='/privacy',terms=path==='/terms';const h=privacy?'Keep game data on this device':terms?'Use fictional goods for fun':'This board is not open';const body=privacy?'<p>Closing Bell stores your mute choice and an active room seat in this browser. Room state and trades are stored by Closing Bell so players can reconnect. It does not use accounts, analytics, ads, or third-party services.</p><p>Demo data uses separate keys beginning with <code>demo:closing-bell</code>.</p>':terms?'<p>Closing Bell is a free game. It has no real assets, money, betting, prizes, or financial advice.</p>':'<p>The page you requested does not exist.</p><p><a href="/" data-route>Return to the game</a></p>';app.innerHTML=nav()+'<main id="main" tabindex="-1" class="copy-page"><article><h1>'+h+'</h1>'+body+'</article></main>'+foot()+'<div class="route-note" aria-live="polite"></div>';wireLinks();setTimeout(()=>app.querySelector<HTMLElement>('#main')?.focus());}
function card(g:Good|Omit<Good,'holding'>,i:number,held:number,shared=false){const buttons=shared?(room?.phase==='playing'?'<button data-remote="sell" data-good="'+g.id+'" aria-label="Sell one '+g.name+'">Sell</button><button data-remote="buy" data-good="'+g.id+'" aria-label="Buy one '+g.name+'">Buy</button>':'<span>Trades open when the host starts.</span>'):'<button data-action="sell" data-good="'+i+'" aria-label="Sell one '+g.name+'">Sell</button><button data-action="buy" data-good="'+i+'" aria-label="Buy one '+g.name+'">Buy</button>';return'<article class="good '+g.color+'"><div class="good-title"><span class="good-mark">'+g.mark+'</span><div><h3>'+g.name+'</h3><p>Held: <b>'+held+'</b></p></div></div><p class="price">'+g.price+'</p><div class="trade">'+buttons+'</div></article>';}
function board(g:Game){return'<section class="game-shell" aria-label="Practice market game"><div class="board-top"><div><p class="eyebrow">Practice market</p><p class="status" aria-live="polite">'+g.status+'</p></div><div class="timer"><span>Time to bell</span><strong data-timer>'+time(g.seconds)+'</strong></div></div>'+progress(g.seconds,g.total)+'<div class="headline"><span aria-hidden="true">!</span><div><p class="eyebrow">Public headline</p><h2>'+(g.headline<0?'The market opens. Make the first trade.':news[g.headline][0])+'</h2></div></div><p class="rumor"><strong>Private rumor:</strong> Finish with two tin robots.</p><div class="goods">'+g.goods.map((x,i)=>card(x,i,x.holding)).join('')+'</div><aside class="wallet"><div><span>Tickets</span><strong data-cash>'+g.cash+'</strong></div><div><span>Desk value</span><strong>'+portfolio(g)+'</strong></div><div><span>Holdings</span><strong>'+g.goods.reduce((a,x)=>a+x.holding,0)+'</strong></div></aside><div class="game-controls"><button class="button quiet" data-action="pause">Pause</button><button class="button quiet" data-action="mute">Sound: '+(g.mute?'off':'on')+'</button></div></section>';}
function portfolio(g:Game){return g.cash+g.goods.reduce((a,x)=>a+x.price*x.holding,0);}
function renderDemo(){const g=game!;const setup='<section class="setup-card"><div><p class="eyebrow">90-second practice table</p><h2>Open the market</h2><p>Try three fictional goods before the practice bell.</p><ul><li>Each player starts with 180 tickets.</li><li>News arrives every 12 seconds.</li><li>Finish with two tin robots.</li></ul></div><div class="setup-actions"><label for="seat-name">Your seat name</label><input id="seat-name" maxlength="14" value="Seat 1"><button class="button primary" data-action="start">Start the round <span>→</span></button><button class="button quiet" data-action="mute">Sound: '+(g.mute?'off':'on')+'</button></div></section>';app.innerHTML=nav()+'<aside class="demo-banner" aria-label="Demo mode">Demo — sample data, nothing is saved <button data-action="reset">Reset demo</button><button data-action="real">Start for real</button></aside><main id="main" tabindex="-1"><section class="hero"><div class="hero-copy"><p class="eyebrow">A short fictional-goods game</p><h1>Trade funny goods before the bell</h1><p class="lede">For friends who want one lively market round with a clear ending.</p><div class="hero-actions"><a class="button primary" href="/demo" data-route>Try it with sample data <span>→</span></a><span>Opens a 90-second practice round.</span></div><ul class="facts"><li>No accounts</li><li>No real money</li><li>Demo data stays here</li></ul></div><figure class="hero-art"><img src="/assets/market-floor.webp" srcset="/assets/market-floor-small.webp 720w, /assets/market-floor.webp 1200w" sizes="(max-width:700px) 100vw,45vw" width="1200" height="800" alt="A brass closing bell hangs over three fictional goods on a colourful market floor."></figure></section><section class="play-area">'+(g.phase==='setup'?setup:board(g))+'</section><section class="how"><h2>How the round works</h2><ol><li><b>Pick a seat.</b><span>Start with 180 tickets and three goods.</span></li><li><b>Read the news.</b><span>Public headlines change every market price.</span></li><li><b>Trade to the bell.</b><span>Holdings liquidate when the bell rings.</span></li></ol></section></main>'+foot()+'<div class="route-note" aria-live="polite"></div><dialog class="pause-dialog"><h2>Market paused</h2><p>Your prices and holdings are safe here.</p><button class="button primary" data-action="resume">Resume market</button></dialog>';wireLinks();app.querySelectorAll<HTMLElement>('[data-action]').forEach(x=>x.onclick=()=>action(x.dataset.action!,Number(x.dataset.good)));}
function action(a:string,i=0){const g=game!;if(a==='start'){g.phase='playing';headline(g);renderDemo();return;}if(a==='reset'){localStorage.removeItem('demo:closing-bell:best');game=newGame();renderDemo();return;}if(a==='real'){history.pushState({},'','/');game=null;route();return;}if(a==='mute'){g.mute=!g.mute;localStorage.setItem('closing-bell:mute',g.mute?'yes':'no');renderDemo();return;}if(a==='pause'){app.querySelector<HTMLDialogElement>('dialog')?.showModal();return;}if(a==='resume'){app.querySelector<HTMLDialogElement>('dialog')?.close();last=performance.now();return;}if(g.phase!=='playing')return;const x=g.goods[i];if(a==='buy'){if(g.cash<x.price)return notice('Not enough tickets. Sell a holding first.');g.cash-=x.price;x.holding++;g.status='Bought one '+x.name+' for '+x.price+' tickets.';}else if(a==='sell'){if(!x.holding)return notice('You do not hold '+x.name+' yet.');g.cash+=x.price;x.holding--;g.status='Sold one '+x.name+' for '+x.price+' tickets.';}renderDemo();}
function headline(g:Game){g.headline=(g.headline+1)%news.length;const n=news[g.headline];g.goods.forEach((x,i)=>x.price=Math.max(8,x.price+n[1][i]));g.status=n[0];}
function end(g:Game){g.phase='finished';const final=portfolio(g);localStorage.setItem('demo:closing-bell:best',String(Math.max(final,Number(localStorage.getItem('demo:closing-bell:best')||0))));renderDemo();const p=app.querySelector('.play-area')!;p.innerHTML='<section class="end-card"><p class="eyebrow">Closing report</p><h2>The bell rang</h2><p>You finished with <strong>'+final+' tickets</strong>.</p><button class="button primary" data-action="restart">Play another round <span>→</span></button></section>';p.querySelector<HTMLElement>('[data-action]')!.onclick=()=>{game=newGame();game.phase='playing';headline(game);renderDemo();};}
function setupRoom(){return'<section class="room-setup"><div><p class="eyebrow">3–8 player room</p><h1>Trade fictional goods with friends</h1><p class="lede">Create a room, share its five-letter code, then trade together until the bell.</p><ul class="facts"><li>No accounts</li><li>No real money</li><li>Reconnect after reload</li></ul></div><form class="room-form"><label for="remote-name">Your seat name</label><input id="remote-name" name="name" maxlength="14" required value="Trader"><button class="button primary" name="intent" value="create">Create a room <span>→</span></button><label for="room-code">Join a room code</label><input id="room-code" name="code" maxlength="5" pattern="[A-Za-z0-9]{5}" placeholder="ABCDE"><button class="button" name="intent" value="join">Join this room</button><p class="connection" aria-live="polite">'+(error||'Room state is checked by the game server.')+'</p></form></section>';}
function remoteBoard(r:Room){const me=r.players.find(x=>x.isYou);const host=me?.id===r.hostId;return'<section class="game-shell" aria-label="Shared market game"><div class="board-top"><div><p class="eyebrow">Room '+r.code+' · '+r.players.length+'/8 seats</p><p class="status" aria-live="polite">'+(r.phase==='lobby'?'Waiting for three players. Share the room code.':r.headline)+'</p></div><div class="timer"><span>'+(r.phase==='lobby'?'Room code':'Time to bell')+'</span><strong>'+(r.phase==='lobby'?r.code:time(r.seconds))+'</strong></div></div>'+(r.phase==='lobby'?'':progress(r.seconds,r.total))+'<div class="headline"><span aria-hidden="true">!</span><div><p class="eyebrow">'+(r.phase==='lobby'?'Invite friends':'Public headline')+'</p><h2>'+(r.phase==='lobby'?'Share '+r.code+'. The host can open the market at three players.':r.headline)+'</h2></div></div><p class="rumor"><strong>Private rumor:</strong> '+(r.objective||'Reconnect to your seat.')+'</p><div class="goods">'+r.goods.map((g,i)=>card(g,i,me?.holdings[i]||0,true)).join('')+'</div><aside class="wallet"><div><span>Tickets</span><strong>'+ (me?.cash??0)+'</strong></div><div><span>Holdings</span><strong>'+(me?.holdings.reduce((a,x)=>a+x,0)??0)+'</strong></div></aside><section class="players"><h2>Players</h2><ul>'+r.players.map(x=>'<li>'+x.name+(x.isYou?' (you)':'')+' <span>'+(x.connected?'connected':'reconnecting')+'</span></li>').join('')+'</ul></section>'+(r.phase==='lobby'?(host?'<div class="game-controls"><button class="button primary" data-remote="start">Open the market</button></div>':'<p>Only the host opens the market once three players arrive.</p>'):'')+(r.phase==='finished'?'<section class="end-card"><p class="eyebrow">Closing report</p><h2>The bell rang</h2><p>Your holdings were sold at the last market price.</p></section>':'')+'</section>';}
function renderRoom(){app.innerHTML=nav()+'<main id="main" tabindex="-1" class="room-page">'+(room?remoteBoard(room):setupRoom())+'<section class="how"><h2>How the shared round works</h2><ol><li><b>Create a room.</b><span>Share the five-letter code with two to seven friends.</span></li><li><b>Open the market.</b><span>The host starts when three players have joined.</span></li><li><b>Trade to the bell.</b><span>The game server checks every trade and saves room state.</span></li></ol></section></main>'+foot()+'<div class="route-note" aria-live="polite"></div>';wireLinks();app.querySelector<HTMLFormElement>('form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const intent=String((e as SubmitEvent).submitter?.getAttribute('value')||'create');connect(()=>send({type:intent,name:f.get('name'),code:String(f.get('code')||'').toUpperCase()}));});app.querySelectorAll<HTMLElement>('[data-remote]').forEach(x=>x.onclick=()=>send({type:x.dataset.remote,code:room?.code,token:saved()?.token,goodId:x.dataset.good,side:x.dataset.remote}));}
function url(){return location.hostname==='closing-bell.sociobot.in'?'wss://closing-bell-realtime.sociobot.in':'ws://127.0.0.1:8080';}
function connect(open?:()=>void){if(ws&&(ws.readyState===WebSocket.OPEN||ws.readyState===WebSocket.CONNECTING)){if(open)ws.addEventListener('open',open,{once:true});return;}ws=new WebSocket(url());if(open)ws.addEventListener('open',open,{once:true});ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='error'){error=m.message;notice(error);if(!room)renderRoom();return;}if(m.type==='state'){room=m.room;const me=room!.players.find((x:Player)=>x.isYou);if(me)localStorage.setItem(roomKey,JSON.stringify({code:room!.code,token:me.id}));error='';renderRoom();}};ws.onerror=()=>{error='The room service is unavailable. Check your connection and try again.';if(!room)renderRoom();};ws.onclose=()=>{if(room)notice('Connection lost. Reopen this page to reconnect your saved seat.');};}
function saved():{code:string;token:string}|null{try{return JSON.parse(localStorage.getItem(roomKey)||'null');}catch{return null;}}
function restore(){const s=saved();if(s&&!room)connect(()=>send({type:'reconnect',code:s.code,token:s.token}));}
function send(x:Record<string,unknown>){if(ws?.readyState!==WebSocket.OPEN)return notice('Connecting to the room service. Try again in a moment.');ws.send(JSON.stringify(x));}
function loop(t:number){if(!last)last=t;acc+=Math.min(250,t-last);last=t;const g=game;if(g?.phase==='playing'&&!document.hidden&&!app.querySelector<HTMLDialogElement>('dialog')?.open)while(acc>=1000){g.seconds--;acc-=1000;if((g.total-g.seconds)%12===0)headline(g);if(g.seconds<=0){end(g);break;}const tm=app.querySelector('[data-timer]');if(tm)tm.textContent=time(g.seconds);const bar=app.querySelector<HTMLProgressElement>('.progress');if(bar)bar.value=g.seconds;}requestAnimationFrame(loop);}
window.addEventListener('popstate',()=>{game=null;room=null;route();});window.addEventListener('keydown',e=>{if(e.key==='Escape')app.querySelector<HTMLDialogElement>('dialog[open]')?.close();});route();requestAnimationFrame(loop);
